name: campfire-chat
version: '1.0.0'
main: me.irinque.CampfireChat.Main
api-version: '1.21'
authors: [irinque]
website: https://t.me/irinque
commands:
  campfire-chat:
    description: "CampfireChat commands"
    aliases: [cfc]